### ISSUE TITLE
Menü Icons iOS unsichtbar

### ISSUE THREAD

**Issue by yuki-93** [Jugendhackt/JugendhacktApp#1]
Die Menü-Icons werden bei iOS weder mit Chrome noch mit Safari angezeigt wird. SVG kann iOS eigentlich. Vielleicht Problem mit den Feather Icons? Klickbar sind die Icons aber.

- Untersuchen, was das Problem ist
- macOS geht? 
- Am besten über Kabel versuche die Dev-Tools von der Handyapp zu bekommen
- Vielleicht nur ein Problem mit Alpha-Kanal?

**Comment by LarsVomMars** [comment]
Scheint nicht an FeatherIcons zu liegen (gibt zmd. kein Issue darueber).
Unter 3 anderen IOS Geraeten reproduziert, werden auch keine Icons angezeigt
Unter 1x MacOS reproduziert

**Comment by ann0see** [comment]
Hängt denke ich nicht mit Feather Icons zusammen. Wenn ich im CSS bei #app die position: fixed auf position: static setze, sind die Icons sichtbar. Wahrscheinlich ist das ein Layoutproblem
