### ISSUE TITLE
Image Viewer

### ISSUE THREAD

**Issue by Mondanzo** [Jugendhackt/JugendhacktApp#12]
Image Viewer um das öffnen von anderen Tabs zu vermeiden und besser Kompatibilität mit der App zu gewährleisten.

**Comment by LarsVomMars** [comment]
Hab dafuer mal selber ein Tool angefangen zu schreiben, was noch nicht ganz funktioniert, sonst irgendwas wie BigPicture.js?

**Comment by Mondanzo** [comment]
Ich hoffe einfach mal du verwechselst gerade etwas mit BigPicture.js @LarsVomMars

**Comment by LarsVomMars** [comment]
https://github.com/henrygd/bigpicture

Oder was meinst du mit Image Viewer @Mondanzo?

**Comment by Mondanzo** [comment]
Doch genau sowas meine Ich aber dachte du meinst das hier: [https://github.com/josephernest/bigpicture.js](https://github.com/josephernest/bigpicture.js)

**Comment by LarsVomMars** [comment]
Achsooo, ok :D

**Comment by Mondanzo** [comment]
#15
