### ISSUE TITLE
Install-Anleitung Erweiterung

### ISSUE THREAD

**Issue by yuki-93** [Jugendhackt/JugendhacktApp#2]
Die Installanleitung sollte ggf. etwas erweitert werden. Punkte die evtl. sinnvoll wären zu erwähnen:
- ServiceWorker / Caching vs. Dev-Mode
- ...

**Comment by marvinborner** [comment]
Ich denke eigentlich, dass unsere instructions ausreichen sollten.

**Comment by LarsVomMars** [comment]
Habe noch eine kleine Anleitung zum Setup von MariaDB/Mysql geaddet.
