### ISSUE TITLE
[ERR_HTTP_HEADERS_SENT]

### ISSUE THREAD

**Issue by LarsVomMars** [Jugendhackt/JugendhacktApp#21]
Fix `Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client`

This error should be investigated further. It occurs on multiple paths/actions.

Add your occurrences:
- push.js: POST to /send

# Some material
* https://stackoverflow.com/questions/7042340/error-cant-set-headers-after-they-are-sent-to-the-client

**Comment by marvinborner** [comment]
This is quite obvious and I have fixed it before in 795c813b999c54821285d9d938f796d4fae7a5ec but you changed it back again: If an error occurred you can't use res.json/res.send as these would set the headers again.

**Comment by LarsVomMars** [comment]
At least for me this hasn't been working either.
But it also occurred in dbController.js somewhere i cannot remember atm

**Comment by LarsVomMars** [comment]
After some testing around again it didn't occur at all
