### ISSUE TITLE
Split dbController into responding files to avoid merge conflicts

### ISSUE THREAD

**Issue by Mondanzo** [Jugendhackt/JugendhacktApp#31]
Currently the dbController is quite overloaded with functionality for all kind of requests and should be seperated into the single router files to sort them better and should mostly manage the connections but not gathering the resources

**Comment by LarsVomMars** [comment]
Already thought about doing it, just didn't find the time.

I will think about something clever.

**Comment by LarsVomMars** [comment]
I've got an idea on which i will start working in next to no time.

**Comment by LarsVomMars** [comment]
Finished it; will debug and test all the remaining parts later today!

**Comment by LarsVomMars** [comment]
Done
