### ISSUE TITLE
CI und CD mit travis

### ISSUE THREAD

**Issue by yuki-93** [Jugendhackt/JugendhacktApp#4]
Continous Integration und Delivery wäre nice damit wir nicht händisch deployen müssen. Travis ist zudem bei OpenSource Repos in Github kostenlos \o/ und hat eine yaml File als Config.

**Comment by niccokunzmann** [comment]
Schritte für CI:

- [x] .travis.yml erstellen
- [x] auf https://travis-ci.org/organizations/Jugendhackt/repositories die app aktivieren

Ich habe es aktiviert, weil ich Admin-Rechte habe. Ansonsten wäre es eine Pull-Request geworden. Der nächste Push an den master branch müsste dann von Travis ausgeführt werden.

TODO, mache ich nicht.

- [x] Build badge in die README [![Build Status](https://travis-ci.com/Jugendhackt/JugendhacktApp.svg?branch=master)](https://travis-ci.com/Jugendhackt/JugendhacktApp) `[![Build Status](https://travis-ci.com/Jugendhackt/JugendhacktApp.svg?branch=master)](https://travis-ci.com/Jugendhackt/JugendhacktApp)`
- [x] node version eintragen (build failed, siehe https://travis-ci.com/Jugendhackt/JugendhacktApp/builds/125367915)
- [x] pakete installieren
- [x] zeug bauen
- [ ] tests laufen lassen

**Comment by marvinborner** [comment]
We still need to add some tests but build passes.
