### ISSUE TITLE
Unit-Testing

### ISSUE THREAD

**Issue by yuki-93** [Jugendhackt/JugendhacktApp#5]
Zusammen mit #4 (CI und CD) zusammen wären Unit-Tests sinnvoll, damit man auch sicher ist, das nix kaputt geht.

**Comment by marvinborner** [comment]
Ich habe jetzt mal einen simplen testing test case und das mocha testing framework geaddet - wenn jemand Lust hat, dürfen gerne Tests für alle möglichen Funktionen und files geschrieben werden.

Ich close jetzt diesen issue, da eine solide Grundlage gebaut wurde, um Tests zu erstellen.
