### ISSUE TITLE
Benachrichtigungen für aktuelle Infos

### ISSUE THREAD

**Issue by yuki-93** [Jugendhackt/JugendhacktApp#6]
Es sollte eine Art Benachrichtigungen geben. Beispiel von #jhhh19 Info an Teilis eine eigene Flasche mitzubringen.

**Wie sollten die realisiert werden?**
- Websockets?
- Reicht auch Polling alle x Minuten?

**Quelle der Benachrichtigungen?**
- zulip/#ankündigungen? 
- Eintrag von Admin?

**Comment by marvinborner** [comment]
Ich würde eher Websockets mit service worker pushing Funktionen nutzen - das sollte ganz gut funktionieren (auch mit geschlossenem Tab/Fenster)

**Comment by marvinborner** [comment]
Also das sollte meiner Meinung nach jetzt mit der Push API des service workers und der backend web-push library gefixet sein. Ein Admin kann jetzt per request an /push/send eine Nachricht schicken, welche an alle anderen clients gebroadcastet wird.
