### ISSUE TITLE
Share DB structure

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [Jugendhackt/JugendhacktApp#9]
Could you please share the expected data base structure? Without this it won't be possible to run the application.

**Comment by Mondanzo** [comment]
The structure for the table gets created automatically. You can check the dbController for some details about the structure.

**Comment by marvinborner** [comment]
Just create a empty database, add a user and grant the permissions to the database and edit the .env file according to your needs. If you want to use the zulip API you also need to generate a API key or ask us to give you the needed keys.
